- hosts: localhost
  gather_facts: false
  tags:
    - image
  roles:
    - role: image/fetch
      tags:
        - fetch
    - role: image/create
      tags:
        - create
    - role: image/resize
      tags:
        - resize
    - role: image/mount
      tags:
        - mount
    - role: image/install
      tags:
        - install

- name: bootstrap image for ansible
  hosts: kiosk
  gather_facts: false
  tags:
    - configure
  roles:
    - bootstrap
    - kiosk

- name: cleanup
  hosts: localhost
  tags:
    - cleanup
  roles:
    - image/cleanup
