# RASPBERRY PI KIOSK USING ARCH LINUX
# Lars Kellogg-Stedman <lars@oddbit.com>
# http://github.com/larsks/rpi-kiosk/

# Download Arch Linux, create a disk image file, create the necessary
# partition layout, create filesystems, mount them, and populate
# them from the Arch Linux tarball.  At the end of this play you will
# have a bootable image with a default Arch configuration.
- hosts: localhost
  gather_facts: false
  tags:
    - image
  roles:
    - role: image/fetch
      tags:
        - fetch
    - role: image/create
      tags:
        - create
    - role: image/resize
      tags:
        - resize
    - role: image/mount
      tags:
        - mount
    - role: image/install
      tags:
        - install

# Perform all the image configuration tasks.
- name: configure the kiosk
  hosts: kiosk
  gather_facts: false
  tags:
    - configure
  roles:
    - role: bootstrap
      tags:
        - bootstrap
    - kiosk

# Ensure that everything is unmounted and the loop device is
# unconfigured.
- name: cleanup
  hosts: localhost
  tags:
    - cleanup
  roles:
    - image/cleanup
