- name: upgrade all packages
  pacman:
    update_cache: true
    upgrade: true

- name: install required packages
  tags:
    - packages
  pacman:
    name: "{{item}}"
    state: installed
  with_items:
    - git
    - nodm
    - openbox
    - unclutter
    - surf
    - dmenu
    - xorg-server
    - "{{xf86_video_driver}}"
    - raspberrypi-firmware-tools
    - wpa_supplicant

- name: install fonts
  tags:
    - fonts
  pacman:
    name: "{{item}}"
    state: installed
  with_items: "{{kiosk_fonts}}"
