- name: install ssh key
  authorized_key:
    user: "{{item}}"
    key: "{{ssh_public_key}}"
  with_items:
    - root

- name: create kiosk user
  user:
    name: "{{autologin_user}}"
    comment: Kiosk User
    shell: /bin/bash

- name: delete default user
  user:
    name: "{{arch_default_user}}"
    state: absent

- name: set root password
  user:
    name: root
    password: "{{root_password}}"
